#!/bin/bash

# Positive numbers
find autogenerated_tables/ -type f -exec sed -r -i 's/\& ([0-9]+\.[0-9]+)/\& \\num{\1}/g' {} \;

# Negative numbers
find autogenerated_tables/ -type f -exec sed -r -i 's/\& \$-\$([0-9]+\.[0-9]+)/\& \\num{-\1}/g' {} \;

find autogenerated_tables/ -type f -exec sed -r -i 's/_position \&/_position (m) \&/g' {} \;

find autogenerated_tables/ -type f -exec sed -r -i 's/yaw \&/yaw (rad) \&/g' {} \;

find autogenerated_tables/ -type f -exec sed -r -i 's/([xy]|position)\\_error \&/\1\\_error (m) \&/g' {} \;

find autogenerated_tables/ -type f -exec sed -r -i 's/yaw\\_error \&/yaw\\_error (rad) \&/g' {} \;

find autogenerated_tables/ -type f -exec sed -r -i 's/(([xy]|yaw)\\_variance)/%\1/g' {} \;
