#!/bin/zsh
echo "Cloning device-tree-xlnx..."
(git clone https://github.com/Xilinx/device-tree-xlnx)
echo "Cloning dtc..."
(git clone https://git.kernel.org/pub/scm/utils/dtc/dtc)
echo "Cloning linux-xlnx..."
(git clone https://github.com/Xilinx/linux-xlnx)
echo "Cloning u-boot-xlnx..."
(git clone https://github.com/Xilinx/u-boot-xlnx)
echo "Cloning linux-adi..."
(git clone https://github.com/analogdevicesinc/linux linux-adi)
echo "Cloning firmware..."
(git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware)
