if (!require("data.table")){
    install.packages("data.table", repos="http://cran.rstudio.com/")
    library("data.table")
}

#source("/home/matt/stargazer/R/stargazer.R")
#source("/home/matt/stargazer/R/stargazer-internal.R")
library("stargazer")
gazebo_stationary_noiseless <- fread("/home/matt/thesis/experiment_data/one_stationary_noiseless/turtlebot1_gazebo_odom.csv", header=T, sep=",")

continuous_stationary_noiseless <- fread("/home/matt/thesis/experiment_data/one_stationary_noiseless/turtlebot1_continuous_filter_odom.csv", header=T, sep=",")

#file_name <- paste0("turtlebot", params$robot, "_discrete_filter_odom.csv")
#discrete <- fread(paste(params$data_dir, params$experiment, file_name, sep="/"), header=T, sep=",")

#file_name <- paste0("turtlebot", params$robot, "_external_pose_count.csv")
#external_count <- fread(paste(params$data_dir, params$experiment, file_name, sep="/"), header=T, sep=",")

#file_name <-paste0("turtlebot", params$robot, "_gps_data.csv")
#gps <- fread(paste(params$data_dir, params$experiment, file_name, sep="/"), header=T, sep=",")

#file_name <-paste0("turtlebot", params$robot, "_noisy_odom_data.csv")
#noisy_odom <- fread(paste(params$data_dir, params$experiment, file_name, sep="/"), header=T, sep=",")

continuous_stationary_noiseless$x_error <- gazebo_stationary_noiseless$x_position - continuous_stationary_noiseless$x_position
continuous_stationary_noiseless$y_error <- gazebo_stationary_noiseless$y_position - continuous_stationary_noiseless$y_position
continuous_stationary_noiseless$yaw_error <- gazebo_stationary_noiseless$yaw - continuous_stationary_noiseless$yaw
continuous_stationary_noiseless$horizontal_error <- sqrt(continuous_stationary_noiseless$x_error ^ 2 + continuous_stationary_noiseless$y_error ^ 2)

gazebo_stationary_noiseless$horizontal_error <- sqrt(gazebo_stationary_noiseless$x_position ^ 2 + gazebo_stationary_noiseless$y_position ^ 2)

pdf("/home/matt/thesis/writing/r_figures/gazebo_odom_drift.pdf")
plot(gazebo_stationary_noiseless$horizontal_error, main="Gazebo Odometry Drift for Stationary Robot with Noiseless Odometry", ylab="Distance from Origin (m)", xlab="Time (.1s)")
dev.off()

pdf("/home/matt/thesis/writing/r_figures/noiseless_continuous_error.pdf")
plot(continuous_stationary_noiseless$horizontal_error, main="Continuous Filter Error", sub="For Stationary Robot with Noiseless Odometry", xlab="Time (.1s)", ylab="Horizontal Position Error (m)")
dev.off()


stargazer(gazebo_stationary_noiseless,
          out="/home/matt/thesis/writing/autogenerated_tables/gazebo_stationary_noiseless_summary.tex",
          table.placement="h",
          label="tab:gazebo_stationary_noiseless_summary",
          title="Ground Truth Noiseless Odometry for Stationary Robot located at Origin",
          digits.extra = 20)

stargazer(continuous_stationary_noiseless,
          out="/home/matt/thesis/writing/autogenerated_tables/continuous_stationary_noiseless_summary.tex",
          table.placement="h",
          label="tab:continuous_stationary_noiseless_summary",
          title="Continuous Filter Estimate for Stationary Robot with Noiseless Odometry",
          digits.extra = 20)
