if (!require("data.table")){
    install.packages("data.table", repos="http://cran.rstudio.com/")
    library("data.table")
}

if (!require("stargazer")){
    install.packages("stargazer", repos="https://cran.rstudio.com/")
    library("stargazer")
}

correct_yaw <- function(yaw) {
    while (yaw > pi) {
        yaw <- yaw - 2*pi
    }
    while (yaw < -1*pi) {
        yaw <- yaw + 2*pi
    }

    return(yaw)
}

vector_correct_yaw <- Vectorize(correct_yaw)

gazebo_stationary_noiseless <- fread("/home/matt/thesis/experiment_data/one_stationary_noiseless/turtlebot1_gazebo_odom.csv", header=T, sep=",")

continuous_stationary_noiseless <- fread("/home/matt/thesis/experiment_data/one_stationary_noiseless/turtlebot1_continuous_filter_odom.csv", header=T, sep=",")

#discrete_stationary_noiseless <- fread("/home/matt/thesis/experiment_data/one_stationary_noiseless/turtlebot1_discrete_filter_odom.csv", header=T, sep=",")

#file_name <- paste0("turtlebot", params$robot, "_external_pose_count.csv")
#external_count <- fread(paste(params$data_dir, params$experiment, file_name, sep="/"), header=T, sep=",")

#file_name <-paste0("turtlebot", params$robot, "_gps_data.csv")
#gps <- fread(paste(params$data_dir, params$experiment, file_name, sep="/"), header=T, sep=",")

#file_name <-paste0("turtlebot", params$robot, "_noisy_odom_data.csv")
#noisy_odom <- fread(paste(params$data_dir, params$experiment, file_name, sep="/"), header=T, sep=",")

continuous_stationary_noiseless$x_error <- gazebo_stationary_noiseless$x_position - continuous_stationary_noiseless$x_position
continuous_stationary_noiseless$y_error <- gazebo_stationary_noiseless$y_position - continuous_stationary_noiseless$y_position
for (i in 1:NROW(continuous_stationary_noiseless$yaw)) {
    yaw <- gazebo_stationary_noiseless$yaw[i] - continuous_stationary_noiseless$yaw[i]

    while (yaw > pi) {
        yaw <- yaw - 2*pi
    }
    while (yaw < -1*pi){
        yaw <- yaw + 2*pi
    }
    continuous_stationary_noiseless$yaw_error[i] <- yaw
}
continuous_stationary_noiseless$horizontal_error <- sqrt(continuous_stationary_noiseless$x_error ^ 2 + continuous_stationary_noiseless$y_error ^ 2)

gazebo_stationary_noiseless$horizontal_error <- sqrt(gazebo_stationary_noiseless$x_position ^ 2 + gazebo_stationary_noiseless$y_position ^ 2)

pdf("/home/matt/thesis/writing/r_figures/gazebo_odom_drift.pdf")
plot(gazebo_stationary_noiseless$horizontal_error, main="Gazebo Odometry Drift for Stationary Robot with Noiseless Odometry", ylab="Distance from Origin (m)", xlab="Time (.1s)")
dev.off()

pdf("/home/matt/thesis/writing/r_figures/noiseless_continuous_error.pdf")
plot(continuous_stationary_noiseless$horizontal_error, main="Continuous Filter Error", sub="For Stationary Robot with Noiseless Odometry", xlab="Time (.1s)", ylab="Horizontal Position Error (m)")
dev.off()


stargazer(gazebo_stationary_noiseless,
          out="/home/matt/thesis/writing/autogenerated_tables/gazebo_stationary_noiseless_summary.tex",
          table.placement="h",
          label="tab:gazebo_stationary_noiseless_summary",
          title="Ground Truth Noiseless Odometry for Stationary Robot located at Origin",
          digits.extra = 20)

stargazer(continuous_stationary_noiseless,
          out="/home/matt/thesis/writing/autogenerated_tables/continuous_stationary_noiseless_summary.tex",
          table.placement="h",
          label="tab:continuous_stationary_noiseless_summary",
          title="Continuous Filter Estimate for Stationary Robot with Noiseless Odometry",
          digits.extra = 20)

gazebo_mobile_noiseless <- fread("/home/matt/thesis/experiment_data/one_mobile_noiseless/turtlebot1_gazebo_odom.csv", header=T, sep=",")

continuous_mobile_noiseless <- fread("/home/matt/thesis/experiment_data/one_mobile_noiseless/turtlebot1_continuous_filter_odom.csv", header=T, sep=",")

continuous_mobile_noiseless$x_error <- gazebo_mobile_noiseless$x_position - continuous_mobile_noiseless$x_position
continuous_mobile_noiseless$y_error <- gazebo_mobile_noiseless$y_position - continuous_mobile_noiseless$y_position
#continuous_mobile_noiseless$yaw_error <- gazebo_mobile_noiseless$yaw - continuous_mobile_noiseless$yaw
for (i in 1:NROW(continuous_mobile_noiseless$yaw)) {
    yaw <- gazebo_mobile_noiseless$yaw[i] - continuous_mobile_noiseless$yaw[i]

    while (yaw > pi) {
        yaw <- yaw - 2*pi
    }
    while (yaw < -1*pi){
        yaw <- yaw + 2*pi
    }
    continuous_mobile_noiseless$yaw_error[i] <- yaw
}

continuous_mobile_noiseless$horizontal_error <- sqrt(continuous_mobile_noiseless$x_error ^ 2 + continuous_mobile_noiseless$y_error ^ 2)

gazebo_mobile_noiseless$horizontal_error <- sqrt(gazebo_mobile_noiseless$x_position ^ 2 + gazebo_mobile_noiseless$y_position ^ 2)

pdf("/home/matt/thesis/writing/r_figures/mobile_noiseless_continuous_error.pdf")
plot(continuous_mobile_noiseless$horizontal_error, main="Continuous Filter Error", sub="For Mobile Robot with Noiseless Odometry", xlab="Time (.1s)", ylab="Horizontal Position Error (m)")
dev.off()

stargazer(gazebo_mobile_noiseless,
          out="/home/matt/thesis/writing/autogenerated_tables/gazebo_mobile_noiseless_summary.tex",
          table.placement="h",
          label="tab:gazebo_mobile_noiseless_summary",
          title="Ground Truth Noiseless Odometry for Mobile Robot located at Origin",
          digits.extra = 20)

stargazer(continuous_mobile_noiseless,
          out="/home/matt/thesis/writing/autogenerated_tables/continuous_mobile_noiseless_summary.tex",
          table.placement="h",
          label="tab:continuous_mobile_noiseless_summary",
          title="Continuous Filter Estimate for Mobile Robot with Noiseless Odometry",
          digits.extra = 20)


gazebo_stationary_noisy <- fread("/home/matt/thesis/experiment_data/one_stationary/turtlebot1_gazebo_odom.csv", header=T, sep=",")
continuous_stationary_noisy <- fread("/home/matt/thesis/experiment_data/one_stationary/turtlebot1_continuous_filter_odom.csv", header=T, sep=",")

continuous_stationary_noisy$x_error <- gazebo_stationary_noisy$x_position - continuous_stationary_noisy$x_position
continuous_stationary_noisy$y_error <- gazebo_stationary_noisy$y_position - continuous_stationary_noisy$y_position

for (i in 1:NROW(continuous_stationary_noisy$yaw)) {
    yaw <- gazebo_stationary_noisy$yaw[i] - continuous_stationary_noisy$yaw[i]

    while (yaw > pi) {
        yaw <- yaw - 2*pi
    }
    while (yaw < -1*pi){
        yaw <- yaw + 2*pi
    }
    continuous_stationary_noisy$yaw_error[i] <- yaw
}

continuous_stationary_noisy$horizontal_error <- sqrt(continuous_stationary_noisy$x_error ^ 2 + continuous_stationary_noisy$y_error ^ 2)
gazebo_stationary_noisy$horizontal_error <- sqrt(gazebo_stationary_noisy$x_position ^ 2 + gazebo_stationary_noisy$y_position ^ 2)

pdf("/home/matt/thesis/writing/r_figures/stationary_noisy_continuous_error.pdf")
plot(continuous_stationary_noisy$horizontal_error, main="Continuous Filter Error", sub="For Stationary Robot with Noisy Odometry", xlab="Time (.1s)", ylab="Horizontal Position Error (m)")
dev.off()

stargazer(gazebo_stationary_noisy,
          out="/home/matt/thesis/writing/autogenerated_tables/gazebo_stationary_noisy_summary.tex",
          table.placement="h",
          label="tab:gazebo_stationary_noisy_summary",
          title="Ground Truth Noisy Odometry for Stationary Robot Located at Origin",
          digits.extra = 20)

stargazer(continuous_stationary_noisy,
          out="/home/matt/thesis/writing/autogenerated_tables/continuous_stationary_noisy_summary.tex",
          table.placement="h",
          label="tab:continuous_stationary_noisy_summary",
          title="Continuous Filter Estimate for Stationary Robot with Noisy Odometry",
          digits.extra = 20)

gazebo_mobile_noisy <- fread("/home/matt/thesis/experiment_data/one_mobile/turtlebot1_gazebo_odom.csv", header=T, sep=",")
continuous_mobile_noisy <- fread("/home/matt/thesis/experiment_data/one_mobile/turtlebot1_continuous_filter_odom.csv", header=T, sep=",")

continuous_mobile_noisy$x_error <- gazebo_mobile_noisy$x_position - continuous_mobile_noisy$x_position
continuous_mobile_noisy$y_error <- gazebo_mobile_noisy$y_position - continuous_mobile_noisy$y_position

for (i in 1:NROW(continuous_mobile_noisy$yaw)) {
    yaw <- gazebo_mobile_noisy$yaw[i] - continuous_mobile_noisy$yaw[i]

    while (yaw > pi) {
        yaw <- yaw - 2*pi
    }
    while (yaw < -1*pi){
        yaw <- yaw + 2*pi
    }
    continuous_mobile_noisy$yaw_error[i] <- yaw
}

continuous_mobile_noisy$horizontal_error <- sqrt(continuous_mobile_noisy$x_error ^ 2 + continuous_mobile_noisy$y_error ^ 2)
gazebo_mobile_noisy$horizontal_error <- sqrt(gazebo_mobile_noisy$x_position ^ 2 + gazebo_mobile_noisy$y_position ^ 2)

pdf("/home/matt/thesis/writing/r_figures/mobile_noisy_continuous_error.pdf")
plot(continuous_mobile_noisy$horizontal_error, main="Continuous Filter Error", sub="For Mobile Robot with Noisy Odometry", xlab="Time (.1s)", ylab="Horizontal Position Error (m)")
dev.off()

stargazer(gazebo_mobile_noisy,
          out="/home/matt/thesis/writing/autogenerated_tables/gazebo_mobile_noisy_summary.tex",
          table.placement="h",
          label="tab:gazebo_mobile_noisy_summary",
          title="Ground Truth Noisy Odometry for Mobile Robot Located at Origin",
          digits.extra = 20)

stargazer(continuous_mobile_noisy,
          out="/home/matt/thesis/writing/autogenerated_tables/continuous_mobile_noisy_summary.tex",
          table.placement="h",
          label="tab:continuous_mobile_noisy_summary",
          title="Continuous Filter Estimate for Mobile Robot with Noisy Odometry",
          digits.extra = 20)



gazebo_filenames <- c("turtlebot1_gazebo_odom.csv", "turtlebot2_gazebo_odom.csv")
gazebo_full_filenames <- lapply(gazebo_filenames, FUN=function(filename){paste("/home/matt/thesis/experiment_data", "two_stationary", filename, sep="/")})
two_stationary_gazebo <- rbindlist(lapply(gazebo_full_filenames, FUN=function(file){fread(file, header=T, sep=",")}))

discrete_filenames <- c("turtlebot1_discrete_filter_odom.csv", "turtlebot2_discrete_filter_odom.csv")
discrete_full_filenames <- lapply(discrete_filenames, FUN=function(filename){paste("/home/matt/thesis/experiment_data", "two_stationary", filename, sep="/")})
two_stationary_discrete <- rbindlist(lapply(discrete_full_filenames, FUN=function(file){fread(file, header=T, sep=",")}))

continuous_filenames <- c("turtlebot1_continuous_filter_odom.csv", "turtlebot2_continuous_filter_odom.csv")
continuous_full_filenames <- lapply(continuous_filenames, FUN=function(filename){paste("/home/matt/thesis/experiment_data", "two_stationary", filename, sep="/")})
two_stationary_continuous <- rbindlist(lapply(continuous_full_filenames, FUN=function(file){fread(file, header=T, sep=",")}))

two_stationary_continuous$x_error <- two_stationary_gazebo$x_position - two_stationary_continuous$x_position
two_stationary_continuous$y_error <- two_stationary_gazebo$y_position - two_stationary_continuous$y_position

for (i in 1:NROW(two_stationary_continuous$yaw)) {
    yaw <- two_stationary_gazebo$yaw[i] - two_stationary_continuous$yaw[i]

    while (yaw > pi) {
        yaw <- yaw - 2*pi
    }
    while (yaw < -1*pi){
        yaw <- yaw + 2*pi
    }
    two_stationary_continuous$yaw_error[i] <- yaw
}

two_stationary_continuous$horizontal_error <- sqrt(two_stationary_continuous$x_error ^ 2 + two_stationary_continuous$y_error ^ 2)
two_stationary_gazebo$horizontal_error <- sqrt(two_stationary_gazebo$x_position ^ 2 + two_stationary_gazebo$y_position ^ 2)

pdf("/home/matt/thesis/writing/r_figures/two_stationary_continuous_error.pdf")
plot(continuous_mobile_noisy$horizontal_error, main="Continuous Filter Error", sub="For Stationary Robots with Noisy Odometry", xlab="Time (.1s)", ylab="Horizontal Position Error (m)")
dev.off()

pdf("/home/matt/thesis/writing/r_figures/two_stationary_discrete_error.pdf")
plot(continuous_mobile_noisy$horizontal_error, main="Discrete Filter Error", sub="For Stationary Robots with Noisy Odometry", xlab="Time (.1s)", ylab="Horizontal Position Error (m)")
dev.off()

stargazer(two_stationary_continuous,
          out="/home/matt/thesis/writing/autogenerated_tables/two_stationary_continuous_summary.tex",
          table.placement="h",
          label="tab:two_stationary_continuous_mobile",
          title="Continuous Filter Estimate for Stationary Robots with Noisy Odometry",
          digits.extra = 20)

stargazer(two_stationary_discrete,
          out="/home/matt/thesis/writing/autogenerated_tables/two_stationary_discrete_summary.tex",
          table.placement="h",
          label="tab:two_stationary_discrete_mobile",
          title="Discrete Filter Estimate for Stationary Robots with Noisy Odometry",
          digits.extra = 20)


gazebo_filenames <- c("turtlebot1_gazebo_odom.csv", "turtlebot2_gazebo_odom.csv")
gazebo_full_filenames <- lapply(gazebo_filenames, FUN=function(filename){paste("/home/matt/thesis/experiment_data", "two_mobile", filename, sep="/")})
two_mobile_gazebo <- rbindlist(lapply(gazebo_full_filenames, FUN=function(file){fread(file, header=T, sep=",")}))

discrete_filenames <- c("turtlebot1_discrete_filter_odom.csv", "turtlebot2_discrete_filter_odom.csv")
discrete_full_filenames <- lapply(discrete_filenames, FUN=function(filename){paste("/home/matt/thesis/experiment_data", "two_mobile", filename, sep="/")})
two_mobile_discrete <- rbindlist(lapply(discrete_full_filenames, FUN=function(file){fread(file, header=T, sep=",")}))

continuous_filenames <- c("turtlebot1_continuous_filter_odom.csv", "turtlebot2_continuous_filter_odom.csv")
continuous_full_filenames <- lapply(continuous_filenames, FUN=function(filename){paste("/home/matt/thesis/experiment_data", "two_mobile", filename, sep="/")})
two_mobile_continuous <- rbindlist(lapply(continuous_full_filenames, FUN=function(file){fread(file, header=T, sep=",")}))

two_mobile_continuous$x_error <- two_mobile_gazebo$x_position - two_mobile_continuous$x_position
two_mobile_continuous$y_error <- two_mobile_gazebo$y_position - two_mobile_continuous$y_position

for (i in 1:NROW(two_mobile_continuous$yaw)) {
    yaw <- two_mobile_gazebo$yaw[i] - two_mobile_continuous$yaw[i]

    while (yaw > pi) {
        yaw <- yaw - 2*pi
    }
    while (yaw < -1*pi){
        yaw <- yaw + 2*pi
    }
    two_mobile_continuous$yaw_error[i] <- yaw
}

two_mobile_continuous$horizontal_error <- sqrt(two_mobile_continuous$x_error ^ 2 + two_mobile_continuous$y_error ^ 2)
two_mobile_gazebo$horizontal_error <- sqrt(two_mobile_gazebo$x_position ^ 2 + two_mobile_gazebo$y_position ^ 2)

pdf("/home/matt/thesis/writing/r_figures/two_mobile_continuous_error.pdf")
plot(continuous_mobile_noisy$horizontal_error, main="Continuous Filter Error", sub="For Mobile Robots with Noisy Odometry", xlab="Time (.1s)", ylab="Horizontal Position Error (m)")
dev.off()

pdf("/home/matt/thesis/writing/r_figures/two_mobile_discrete_error.pdf")
plot(continuous_mobile_noisy$horizontal_error, main="Discrete Filter Error", sub="For Mobile Robots with Noisy Odometry", xlab="Time (.1s)", ylab="Horizontal Position Error (m)")
dev.off()

stargazer(two_mobile_continuous,
          out="/home/matt/thesis/writing/autogenerated_tables/two_mobile_continuous_summary.tex",
          table.placement="h",
          label="tab:two_mobile_continuous_mobile",
          title="Continuous Filter Estimate for Mobile Robots with Noisy Odometry",
          digits.extra = 20)

stargazer(two_mobile_discrete,
          out="/home/matt/thesis/writing/autogenerated_tables/two_mobile_discrete_summary.tex",
          table.placement="h",
          label="tab:two_mobile_discrete_mobile",
          title="Discrete Filter Estimate for Mobile Robots with Noisy Odometry",
          digits.extra = 20)
